export var SERIES_DETAILS = [
  { slug: "star-trek-the-original-series", title: "Star Trek: The Original Series", badge: "Serie | 1966-1969", releaseLabel: "1966-1969", timelineLabel: "2265-2269", continuity: "Linea principal", summary: "La mision de Kirk, Spock y McCoy define el ADN de Star Trek.", facts: ["3 temporadas", "79 episodios", "La Enterprise clasica", "Base del canon Trek"] },
  { slug: "star-trek-the-animated-series", title: "Star Trek: The Animated Series", badge: "Serie | 1973-1974", releaseLabel: "1973-1974", timelineLabel: "2269-2270", continuity: "Linea principal", summary: "Continuacion animada de la tripulacion clasica con mayor libertad visual.", facts: ["2 temporadas", "22 episodios", "Reparto clasico en voces", "Expansion del periodo T.O.S."] },
  { slug: "star-trek-enterprise", title: "Star Trek: Enterprise", badge: "Serie | 2001-2005", releaseLabel: "2001-2005", timelineLabel: "2151-2155", continuity: "Linea principal", summary: "Precuela sobre los primeros pasos humanos hacia la futura Federacion.", facts: ["4 temporadas", "98 episodios", "Capitan Archer", "Era anterior a T.O.S."] },
  { slug: "star-trek-short-treks", title: "Star Trek: Short Treks", badge: "Serie | 2018-2020", releaseLabel: "2018-2020", timelineLabel: "2239-3181", continuity: "Linea principal", summary: "Antologia de historias cortas repartidas entre distintas eras Trek.", facts: ["2 temporadas", "10 episodios", "Formato breve", "Varias epocas del canon"] },
  { slug: "star-trek-discovery", title: "Star Trek: Discovery", badge: "Serie | 2017-2024", releaseLabel: "2017-2024", timelineLabel: "2256-2258 y 3188-3191", continuity: "Linea principal", summary: "Empieza como precuela de T.O.S. y termina en el futuro remoto.", facts: ["5 temporadas", "65 episodios", "Michael Burnham", "Salto al siglo XXXII"] },
  { slug: "star-trek-strange-new-worlds", title: "Star Trek: Strange New Worlds", badge: "Serie | 2022-presente", releaseLabel: "2022-presente", timelineLabel: "2259-2261", continuity: "Linea principal", summary: "La Enterprise de Pike recupera el espiritu de aventura clasica.", facts: ["3 temporadas", "30 episodios", "Pike y Spock", "Antesala de T.O.S."] },
  { slug: "star-trek-the-next-generation", title: "Star Trek: The Next Generation", badge: "Serie | 1987-1994", releaseLabel: "1987-1994", timelineLabel: "2364-2370", continuity: "Linea principal", summary: "Picard relanza Star Trek para una nueva generacion.", facts: ["7 temporadas", "178 episodios", "Enterprise-D", "Renacimiento televisivo"] },
  { slug: "star-trek-deep-space-nine", title: "Star Trek: Deep Space Nine", badge: "Serie | 1993-1999", releaseLabel: "1993-1999", timelineLabel: "2369-2375", continuity: "Linea principal", summary: "Drama coral, politico y belico en una estacion espacial fronteriza.", facts: ["7 temporadas", "176 episodios", "Benjamin Sisko", "Guerra del Dominio"] },
  { slug: "star-trek-voyager", title: "Star Trek: Voyager", badge: "Serie | 1995-2001", releaseLabel: "1995-2001", timelineLabel: "2371-2378", continuity: "Linea principal", summary: "La USS Voyager queda aislada y convierte el regreso a casa en su gran objetivo.", facts: ["7 temporadas", "172 episodios", "Kathryn Janeway", "Cuadrante Delta"] },
  { slug: "star-trek-lower-decks", title: "Star Trek: Lower Decks", badge: "Serie | 2020-2024", releaseLabel: "2020-2024", timelineLabel: "2380-2382", continuity: "Linea principal", summary: "Comedia animada sobre oficiales subalternos con gran amor por el canon Trek.", facts: ["5 temporadas", "50 episodios", "USS Cerritos", "Humor y referencias"] },
  { slug: "star-trek-prodigy", title: "Star Trek: Prodigy", badge: "Serie | 2021-2024", releaseLabel: "2021-2024", timelineLabel: "2383-2385", continuity: "Linea principal", summary: "Un grupo joven aprende a convertirse en tripulacion a bordo del Protostar.", facts: ["2 temporadas", "40 episodios", "Vinculada a Voyager", "Entrada ideal para nuevos publicos"] },
  { slug: "star-trek-picard", title: "Star Trek: Picard", badge: "Serie | 2020-2023", releaseLabel: "2020-2023", timelineLabel: "2399-2402", continuity: "Linea principal", summary: "Jean-Luc Picard vuelve decadas despues para cerrar grandes hilos de su vida.", facts: ["3 temporadas", "30 episodios", "Secuela de TNG", "Cierre de una era"] },
  { slug: "star-trek-starfleet-academy", title: "Star Trek: Starfleet Academy", badge: "Serie | 2026-prevista", releaseLabel: "2026-prevista", timelineLabel: "Siglo XXXII", continuity: "Linea principal", summary: "Nueva etapa Trek centrada en cadetes y vida academica en el siglo XXXII.", facts: ["1 temporada prevista", "10 episodios previstos", "Academia Estelar", "Futuro remoto"] }
];

export var MOVIE_DETAILS = [
  { slug: "star-trek-the-motion-picture", title: "Star Trek: The Motion Picture", badge: "Pelicula | 1979", releaseLabel: "1979", timelineLabel: "2273", continuity: "Linea principal", summary: "La Enterprise refit se enfrenta a V'Ger en el debut cinematografico de la saga.", facts: ["Primera pelicula Trek", "Tripulacion clasica", "Enterprise refit", "Gran escala visual"] },
  { slug: "star-trek-ii-the-wrath-of-khan", title: "Star Trek II: The Wrath of Khan", badge: "Pelicula | 1982", releaseLabel: "1982", timelineLabel: "2285", continuity: "Linea principal", summary: "Khan vuelve para vengarse de Kirk en una de las peliculas mas queridas.", facts: ["Khan Noonien Singh", "Duelo con Kirk", "Referencia del cine Trek", "Gran impacto emocional"] },
  { slug: "star-trek-iii-the-search-for-spock", title: "Star Trek III: The Search for Spock", badge: "Pelicula | 1984", releaseLabel: "1984", timelineLabel: "2285", continuity: "Linea principal", summary: "Kirk desafia a la Flota para recuperar a Spock y mantener unido al grupo.", facts: ["Secuela directa", "Lealtad de la tripulacion", "Periodo clasico", "Centro del arco Spock"] },
  { slug: "star-trek-iv-the-voyage-home", title: "Star Trek IV: The Voyage Home", badge: "Pelicula | 1986", releaseLabel: "1986", timelineLabel: "2286", continuity: "Linea principal", summary: "La tripulacion clasica viaja al siglo XX para salvar la Tierra.", facts: ["Viaje temporal", "Tono mas ligero", "Gran popularidad", "Tema ecologico"] },
  { slug: "star-trek-v-the-final-frontier", title: "Star Trek V: The Final Frontier", badge: "Pelicula | 1989", releaseLabel: "1989", timelineLabel: "2287", continuity: "Linea principal", summary: "La Enterprise persigue una frontera espiritual en una entrega muy singular.", facts: ["Fe y trascendencia", "Kirk-Spock-McCoy", "Entrega polemica", "Busqueda metafisica"] },
  { slug: "star-trek-vi-the-undiscovered-country", title: "Star Trek VI: The Undiscovered Country", badge: "Pelicula | 1991", releaseLabel: "1991", timelineLabel: "2293", continuity: "Linea principal", summary: "La tripulacion original vive una intriga politica clave para la paz con los klingons.", facts: ["Despedida clasica", "Diplomacia klingon", "Fin de una era", "Muy valorada"] },
  { slug: "star-trek-section-31", title: "Star Trek: Section 31", badge: "Pelicula | 2025", releaseLabel: "2025", timelineLabel: "Principios del siglo XXIV", continuity: "Linea principal", summary: "Philippa Georgiou lidera una mision de espionaje de la Seccion 31.", facts: ["Georgiou", "Espionaje Trek", "Streaming", "Era perdida del siglo XXIV"] },
  { slug: "star-trek-generations", title: "Star Trek Generations", badge: "Pelicula | 1994", releaseLabel: "1994", timelineLabel: "2293 y 2371", continuity: "Linea principal", summary: "Puente cinematografico entre la era de Kirk y la de Picard.", facts: ["Encuentro Kirk-Picard", "Nexus", "Inicio del cine TNG", "Transicion de eras"] },
  { slug: "star-trek-first-contact", title: "Star Trek: First Contact", badge: "Pelicula | 1996", releaseLabel: "1996", timelineLabel: "2373", continuity: "Linea principal", summary: "Picard combate a los borg mientras protege el primer contacto con los vulcanos.", facts: ["Enterprise-E", "Borg", "Viaje temporal", "Cima del cine TNG"] },
  { slug: "star-trek-insurrection", title: "Star Trek: Insurrection", badge: "Pelicula | 1998", releaseLabel: "1998", timelineLabel: "2375", continuity: "Linea principal", summary: "Picard se rebela contra una operacion injusta apoyada desde la Federacion.", facts: ["Etica Trek", "Tono cercano a TNG", "Ba'ku", "Desobediencia moral"] },
  { slug: "star-trek-nemesis", title: "Star Trek: Nemesis", badge: "Pelicula | 2002", releaseLabel: "2002", timelineLabel: "2379", continuity: "Linea principal", summary: "La tripulacion de la Enterprise-E se enfrenta a Shinzon en el final del cine TNG.", facts: ["Shinzon", "Cierre TNG", "Tono oscuro", "Importante para Picard"] },
  { slug: "star-trek-2009", title: "Star Trek", badge: "Pelicula | 2009", releaseLabel: "2009", timelineLabel: "2233 y 2258", continuity: "Linea Kelvin", summary: "El incidente del USS Kelvin reinicia la saga en una nueva linea temporal.", facts: ["Linea Kelvin", "Nuevo reparto", "Reinicio", "Gran exito comercial"] },
  { slug: "star-trek-into-darkness", title: "Star Trek Into Darkness", badge: "Pelicula | 2013", releaseLabel: "2013", timelineLabel: "2259", continuity: "Linea Kelvin", summary: "La tripulacion Kelvin se enfrenta a Khan en una entrega mas oscura y explosiva.", facts: ["Khan en Kelvin", "Conspiracion", "Blockbuster", "Segunda pelicula Kelvin"] },
  { slug: "star-trek-beyond", title: "Star Trek Beyond", badge: "Pelicula | 2016", releaseLabel: "2016", timelineLabel: "2263", continuity: "Linea Kelvin", summary: "La Enterprise Kelvin explora mas alla del espacio conocido y cae en la trampa de Krall.", facts: ["Aventura coral", "Krall", "Espiritu mas Trek", "Ultima pelicula Kelvin"] }
];
